# Generated by Django 5.2.1 on 2025-06-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='emergency_contact',
            field=models.IntegerField(),
        ),
    ]
