# Generated by Django 5.2.1 on 2025-06-03 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('birth_place', models.CharField(max_length=50)),
                ('lrn_number', models.CharField(max_length=20)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.gender')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highschool_name', models.CharField(max_length=100)),
                ('strand', models.CharField(max_length=100)),
                ('year_graduated', models.IntegerField()),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('school_address', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_background', to='student.student')),
            ],
        ),
    ]
