# Generated by Django 5.2.1 on 2025-06-04 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_attended', models.CharField(max_length=50)),
                ('degree_earned', models.CharField(max_length=50)),
                ('year_graduated', models.CharField(max_length=50)),
                ('latin_honors', models.CharField(max_length=50)),
                ('thesis_title', models.CharField(max_length=50)),
                ('school_address', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
