# Generated by Django 5.2.1 on 2025-06-04 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_degree_latin_honors_alter_degree_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('contact_number', models.IntegerField()),
                ('relationship', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian', to='student.student')),
            ],
        ),
    ]
