# Generated by Django 5.2.1 on 2025-06-04 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psa', models.BooleanField(default=False)),
                ('tor', models.BooleanField(default=False)),
                ('transfer_credential', models.BooleanField(default=False)),
                ('good_moral', models.BooleanField(default=False)),
                ('photos_2x2', models.BooleanField(default=False)),
                ('med_cert', models.BooleanField(default=False)),
                ('vaccination_card', models.BooleanField(default=False)),
                ('valid_id', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='enrollment.enrollment')),
            ],
        ),
    ]
